@startuml

Product--*ProductCollection
IProductCollection--|>ProductCollection
ContainbleItem--*ProductCollection
ProductCollection--o Dispenser


class Product{
    -Name
    #Price
}

class ProductCollection{
    -products
}

class ContainbleItem{
    +Row
    +Column
    +Count
}

interface IProductCollection{
    +Add()
    +Remove()
    +GetItem()
    +Count()
}

class Dispenser{
    -products
    +ExtractItem()
    +DeliverItem()
    
}

class PaymentTerminal{
    +AddCoins()
    +AddCash()
    +VerifyTransaction(price)
}


@enduml